# Generated by Django 4.1.7 on 2023-03-10 12:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_order', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_product', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('date_order', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата заказа')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_order.ordermodel')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Товар в заказах',
                'verbose_name_plural': 'Товары в заказах',
            },
        ),
    ]
